<?php include 'header.phtml'; ?>
<div class="row">
  <?php include 'sidebar.phtml'; ?>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

    <div class="d-flex justify-content-between flex-wrap 
          flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <form action="" method="post">
        <input class="form-control form-control-dark w-100" type="text" name="search" placeholder="Search" aria-label="Search">
        <input type="submit" class="btn btn-primary" value="Search">
      </form>
    </div>


    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Product Name</th>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col">Stock</th>
           
          </tr>
        </thead>
        <tbody>
        <form action='' method='POST'>
          <?php
          if (isset($data)) {
            foreach ($data as $key => $value) {
              echo "<tr>
                  <td>" . $key . "</td>
                  <td>" . $value->product_name . "</td>
                  <td>" . $value->category . "</td>
                  <td>" . $value->price . "</td>
                  <td>" . $value->stock . "</td>
                  </td>
                  ";
            }
          }
        
          ?>
          </form>
        </tbody>
      </table>
    </div>
