<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

        <ul class="nav flex-column">
        <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/admin/products/addProduct">
              <span data-feather="home"></span>
              Add Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/admin/products-dashboard">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/listProducts">
              <span data-feather="home"></span>
              User List Products
            </a>
          </li>
         
         
    
        

      </div>
    </nav>