<?php include 'header.phtml'; ?>
<div class="row">
  <?php include 'sidebar.phtml'; ?>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

    <div class="d-flex justify-content-between flex-wrap 
          flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <form action="" method="post">
        <input class="form-control form-control-dark w-100" type="text" name="search" placeholder="Search" aria-label="Search">
        <input type="submit" class="btn btn-primary" value="Search">
      </form>
    </div>


    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Product Name</th>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col">Stock</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
        <form action='' method='POST'>
          <?php
          if (isset($data)) {
            foreach ($data as $key => $value) {
              echo "<tr>
                  <td>" . $key . "</td>
                  <td>" . $value->product_name . "</td>
                  <td>" . $value->category . "</td>
                  <td>" . $value->price . "</td>
                  <td>" . $value->stock . "</td>
                  <td><a href='../admin/products/editProduct?id=".$value->_id."' class='btn btn-success'>Edit</a><button class='btn btn-danger' type='submit' name='deleteProduct' value=" . $value->_id . ">Delete</button></td>
                  
                  ";
            }
          }
        
          ?>
          </form>
        </tbody>
      </table>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
           <h1>Quick View</h1>
            <h3 id="product_name"></h3>
            <h3 id="category"></h3>
            <h3 id="price"></h3>
            <h3 id="stock"></h3>
            <h3 id="additional_fields"></h3>
            <h3 id="variations"></h3>
            
          </div>
        
        </div>
      </div>
    </div>

</div>



